#!/usr/bin/env node
/**
 * Generates the kana corpus text source consumed by the app.
 *
 * Output: src/data/kana-corpus.tsv  (tab-separated, '#' comments, UTF-8)
 * Columns: id  category  row  hiragana  katakana  romaji
 *   - `romaji` is pipe-separated; the first entry is the canonical spelling and
 *     the rest are accepted alternates (IME-style: si/shi, tu/tsu, xa/la, ...).
 *
 * Katakana is derived from hiragana by the fixed +0x60 codepoint offset, which
 * holds for the whole U+3041..U+3096 block. Dakuten/handakuten forms are stored
 * precomposed; the app recovers the keystrokes via Unicode NFD decomposition
 * (e.g. が -> か + U+3099), so no keystroke data needs to live in the corpus.
 *
 * Run: npm run corpus
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const OUT = resolve(dirname(fileURLToPath(import.meta.url)), '../src/data/kana-corpus.tsv');

/** hiragana -> katakana (valid across the entire hiragana block) */
const kata = (h) =>
  [...h].map((c) => String.fromCodePoint(c.codePointAt(0) + 0x60)).join('');

/** [hiragana, ...romaji] where romaji[0] is canonical */
const GOJUON = {
  a: [['あ', 'a'], ['い', 'i'], ['う', 'u'], ['え', 'e'], ['お', 'o']],
  ka: [['か', 'ka'], ['き', 'ki'], ['く', 'ku'], ['け', 'ke'], ['こ', 'ko']],
  sa: [['さ', 'sa'], ['し', 'shi', 'si', 'ci'], ['す', 'su'], ['せ', 'se'], ['そ', 'so']],
  ta: [['た', 'ta'], ['ち', 'chi', 'ti'], ['つ', 'tsu', 'tu'], ['て', 'te'], ['と', 'to']],
  na: [['な', 'na'], ['に', 'ni'], ['ぬ', 'nu'], ['ね', 'ne'], ['の', 'no']],
  ha: [['は', 'ha'], ['ひ', 'hi'], ['ふ', 'fu', 'hu'], ['へ', 'he'], ['ほ', 'ho']],
  ma: [['ま', 'ma'], ['み', 'mi'], ['む', 'mu'], ['め', 'me'], ['も', 'mo']],
  ya: [['や', 'ya'], ['ゆ', 'yu'], ['よ', 'yo']],
  ra: [['ら', 'ra'], ['り', 'ri'], ['る', 'ru'], ['れ', 're'], ['ろ', 'ro']],
  wa: [['わ', 'wa'], ['を', 'wo'], ['ん', 'n', 'nn', "n'"]],
};

const DAKUTEN = {
  ga: [['が', 'ga'], ['ぎ', 'gi'], ['ぐ', 'gu'], ['げ', 'ge'], ['ご', 'go']],
  za: [['ざ', 'za'], ['じ', 'ji', 'zi'], ['ず', 'zu'], ['ぜ', 'ze'], ['ぞ', 'zo']],
  da: [['だ', 'da'], ['ぢ', 'di', 'dji'], ['づ', 'du', 'dzu'], ['で', 'de'], ['ど', 'do']],
  ba: [['ば', 'ba'], ['び', 'bi'], ['ぶ', 'bu'], ['べ', 'be'], ['ぼ', 'bo']],
  va: [['ゔ', 'vu']],
};

const HANDAKUTEN = {
  pa: [['ぱ', 'pa'], ['ぴ', 'pi'], ['ぷ', 'pu'], ['ぺ', 'pe'], ['ぽ', 'po']],
};

const SMALL = {
  small: [
    ['ぁ', 'xa', 'la'],
    ['ぃ', 'xi', 'li'],
    ['ぅ', 'xu', 'lu'],
    ['ぇ', 'xe', 'le'],
    ['ぉ', 'xo', 'lo'],
    ['っ', 'xtu', 'ltu', 'xtsu', 'ltsu'],
    ['ゃ', 'xya', 'lya'],
    ['ゅ', 'xyu', 'lyu'],
    ['ょ', 'xyo', 'lyo'],
    ['ゎ', 'xwa', 'lwa'],
  ],
};

/** yoon digraphs: base consonant kana + small ya/yu/yo */
const YOON_BASES = [
  ['き', 'ky', ['kya', 'kyu', 'kyo']],
  ['し', 'sh', ['sha|sya', 'shu|syu', 'sho|syo']],
  ['ち', 'ch', ['cha|tya|cya', 'chu|tyu|cyu', 'cho|tyo|cyo']],
  ['に', 'ny', ['nya', 'nyu', 'nyo']],
  ['ひ', 'hy', ['hya', 'hyu', 'hyo']],
  ['み', 'my', ['mya', 'myu', 'myo']],
  ['り', 'ry', ['rya', 'ryu', 'ryo']],
  ['ぎ', 'gy', ['gya', 'gyu', 'gyo']],
  ['じ', 'j', ['ja|jya|zya', 'ju|jyu|zyu', 'jo|jyo|zyo']],
  ['ぢ', 'dy', ['dya', 'dyu', 'dyo']],
  ['び', 'by', ['bya', 'byu', 'byo']],
  ['ぴ', 'py', ['pya', 'pyu', 'pyo']],
];
const SMALL_Y = ['ゃ', 'ゅ', 'ょ'];

const rows = [];
let id = 0;
const push = (category, row, hira, romaji) => {
  rows.push([String(++id).padStart(3, '0'), category, row, hira, kata(hira), romaji.join('|')]);
};

for (const [set, category] of [
  [GOJUON, 'gojuon'],
  [DAKUTEN, 'dakuten'],
  [HANDAKUTEN, 'handakuten'],
  [SMALL, 'small'],
]) {
  for (const [row, entries] of Object.entries(set)) {
    for (const [hira, ...romaji] of entries) push(category, row, hira, romaji);
  }
}

for (const [base, rowLabel, variants] of YOON_BASES) {
  variants.forEach((spec, i) => push('yoon', rowLabel, base + SMALL_Y[i], spec.split('|')));
}

const header = [
  '# kana-corpus.tsv — generated by scripts/generate-corpus.mjs; do not edit by hand.',
  '# Columns: id\tcategory\trow\thiragana\tkatakana\tromaji(pipe-separated, first = canonical)',
  `# ${rows.length} entries`,
  ['id', 'category', 'row', 'hiragana', 'katakana', 'romaji'].join('\t'),
].join('\n');

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, `${header}\n${rows.map((r) => r.join('\t')).join('\n')}\n`, 'utf8');

const counts = rows.reduce((m, r) => ({ ...m, [r[1]]: (m[r[1]] ?? 0) + 1 }), {});
console.log(`wrote ${rows.length} entries -> ${OUT}`);
console.log(counts);
